name: Delete Previous Releases and Tags

on:
  workflow_dispatch:

jobs:
  delete_releases_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/checkout@v2
        with:
          repository: cli/cli

      - name: Authenticate with GitHub CLI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Delete Releases
        run: |
          gh release list --repo ${{ github.repository }} --json tag_name --jq '.[].tag_name' | while read -r tag_name; do
            gh release delete --repo ${{ github.repository }} "$tag_name" --yes
          done

      - name: Delete Tags
        run: |
          git ls-remote --tags origin | awk '{print $2}' | sed 's#refs/tags/##' | while read -r tag_name; do
            git push --delete origin "$tag_name"
          done
