name: Delete Releases and Tags

on:
  workflow_dispatch:

jobs:
  delete-releases-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete releases and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list --limit 100 | awk '{print $1}' | xargs -I {} gh release delete {}
          git tag -l | xargs git tag -d

      - name: Push changes
        run: |
          git push origin --delete $(git tag -l)
          git push --tags --force
